"""initial schema

Revision ID: 2682f122e71f
Revises:
Create Date: 2026-02-18 08:47:03.472318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2682f122e71f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Extensions required before table creation
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_provider_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("provider_type", sa.String(length=50), nullable=False),
        sa.Column("auth_type", sa.String(length=20), nullable=False),
        sa.Column("api_url", sa.String(length=500), nullable=True),
        sa.Column("api_key_encrypted", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("supports_text", sa.Boolean(), nullable=False),
        sa.Column("supports_vision", sa.Boolean(), nullable=False),
        sa.Column("supports_files", sa.Boolean(), nullable=False),
        sa.Column("model_parameters", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("rate_limited_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.Column("total_tokens_used", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("last_modified_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ai_provider_enabled_priority",
        "ai_provider_configs",
        ["is_enabled", "priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_provider_configs_is_enabled"),
        "ai_provider_configs",
        ["is_enabled"],
        unique=False,
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=12), nullable=False),
        sa.Column("roles", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_api_keys_active", "api_keys", ["is_active"], unique=False)
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_table(
        "crawl_path_patterns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path_pattern", sa.String(length=500), nullable=False),
        sa.Column("data_type", sa.String(length=20), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("fail_count", sa.Integer(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("successful_dno_slugs", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path_pattern"),
    )
    op.create_index(
        "idx_path_patterns_data_type", "crawl_path_patterns", ["data_type"], unique=False
    )
    op.create_table(
        "dnos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("official_name", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("phone", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("region", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("mastr_nr", sa.String(length=50), nullable=True),
        sa.Column("vnb_id", sa.String(length=100), nullable=True),
        sa.Column("primary_bdew_code", sa.String(length=20), nullable=True),
        sa.Column("connection_points_count", sa.Integer(), nullable=True),
        sa.Column("total_capacity_mw", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("crawl_locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("enrichment_status", sa.String(length=20), nullable=True),
        sa.Column("last_enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contact_address", sa.Text(), nullable=True),
        sa.Column("robots_txt", sa.Text(), nullable=True),
        sa.Column("robots_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sitemap_urls", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("sitemap_parsed_urls", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("sitemap_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disallow_paths", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("crawlable", sa.Boolean(), nullable=False),
        sa.Column("crawl_blocked_reason", sa.String(length=100), nullable=True),
        sa.Column("cms_system", sa.String(length=100), nullable=True),
        sa.Column("tech_stack_details", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dnos_mastr_nr"), "dnos", ["mastr_nr"], unique=True)
    op.create_index(
        "ix_dnos_name_trgm",
        "dnos",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_dnos_primary_bdew_code"), "dnos", ["primary_bdew_code"], unique=False)
    op.create_index(op.f("ix_dnos_region"), "dnos", ["region"], unique=False)
    op.create_index(op.f("ix_dnos_slug"), "dnos", ["slug"], unique=True)
    op.create_index(op.f("ix_dnos_status"), "dnos", ["status"], unique=False)
    op.create_index(op.f("ix_dnos_vnb_id"), "dnos", ["vnb_id"], unique=True)
    op.create_table(
        "query_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("interpreted_dno", sa.String(length=255), nullable=True),
        sa.Column("interpreted_year", sa.Integer(), nullable=True),
        sa.Column("interpreted_data_type", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("result_from_cache", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_query_logs_created_at"), "query_logs", ["created_at"], unique=False)
    op.create_table(
        "system_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("service", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("context", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("trace_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_logs_created_at"), "system_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_system_logs_level"), "system_logs", ["level"], unique=False)
    op.create_index(op.f("ix_system_logs_service"), "system_logs", ["service"], unique=False)
    op.create_table(
        "crawl_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dno_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("data_type", sa.String(length=20), nullable=False),
        sa.Column("job_type", sa.String(length=20), nullable=False),
        sa.Column("parent_job_id", sa.Integer(), nullable=True),
        sa.Column("child_job_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("current_step", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("context", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("triggered_by", sa.String(length=255), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dno_id"], ["dnos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_job_id"], ["crawl_jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dno_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("data_type", sa.String(length=20), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("source_format", sa.String(length=20), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extraction_method", sa.String(length=50), nullable=True),
        sa.Column("extraction_notes", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dno_id"], ["dnos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_data_sources_dno_year", "data_sources", ["dno_id", "year"], unique=False)
    op.create_table(
        "dno_bdew_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dno_id", sa.Integer(), nullable=False),
        sa.Column("bdew_code", sa.String(length=20), nullable=False),
        sa.Column("bdew_internal_id", sa.Integer(), nullable=False),
        sa.Column("bdew_company_uid", sa.Integer(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("market_function", sa.String(length=100), nullable=True),
        sa.Column("contact_name", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=100), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("street", sa.String(length=255), nullable=True),
        sa.Column("zip_code", sa.String(length=20), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column(
            "last_synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dno_id"], ["dnos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bdew_code"),
    )
    op.create_index("idx_bdew_code", "dno_bdew_data", ["bdew_code"], unique=False)
    op.create_index(
        "idx_bdew_dno_function", "dno_bdew_data", ["dno_id", "market_function"], unique=True
    )
    op.create_index("idx_bdew_market_function", "dno_bdew_data", ["market_function"], unique=False)
    op.create_index(op.f("ix_dno_bdew_data_dno_id"), "dno_bdew_data", ["dno_id"], unique=False)
    op.create_table(
        "dno_mastr_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dno_id", sa.Integer(), nullable=False),
        sa.Column("mastr_nr", sa.String(length=50), nullable=False),
        sa.Column("acer_code", sa.String(length=50), nullable=True),
        sa.Column("registered_name", sa.String(length=255), nullable=False),
        sa.Column("address_components", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("contact_address", sa.String(length=500), nullable=True),
        sa.Column("region", sa.String(length=255), nullable=True),
        sa.Column("marktrollen", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("closed_network", sa.Boolean(), nullable=False),
        sa.Column("activity_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activity_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("registration_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mastr_last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("connection_points_total", sa.Integer(), nullable=True),
        sa.Column(
            "connection_points_by_level", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("connection_points_ns", sa.Integer(), nullable=True),
        sa.Column("connection_points_ms", sa.Integer(), nullable=True),
        sa.Column("connection_points_hs", sa.Integer(), nullable=True),
        sa.Column("connection_points_hoe", sa.Integer(), nullable=True),
        sa.Column("networks_count", sa.Integer(), nullable=True),
        sa.Column("has_customers", sa.Boolean(), nullable=True),
        sa.Column("closed_distribution_network", sa.Boolean(), nullable=True),
        sa.Column("total_capacity_mw", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("solar_capacity_mw", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("wind_capacity_mw", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("storage_capacity_mw", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("biomass_capacity_mw", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("hydro_capacity_mw", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("solar_units", sa.Integer(), nullable=True),
        sa.Column("wind_units", sa.Integer(), nullable=True),
        sa.Column("storage_units", sa.Integer(), nullable=True),
        sa.Column("stats_computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stats_data_quality", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dno_id"], ["dnos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mastr_nr"),
    )
    op.create_index("idx_mastr_acer", "dno_mastr_data", ["acer_code"], unique=False)
    op.create_index("idx_mastr_nr", "dno_mastr_data", ["mastr_nr"], unique=False)
    op.create_index(op.f("ix_dno_mastr_data_dno_id"), "dno_mastr_data", ["dno_id"], unique=True)
    op.create_table(
        "dno_source_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dno_id", sa.Integer(), nullable=False),
        sa.Column("data_type", sa.String(length=20), nullable=False),
        sa.Column("source_domain", sa.String(length=255), nullable=True),
        sa.Column("source_format", sa.String(length=20), nullable=True),
        sa.Column("last_url", sa.Text(), nullable=True),
        sa.Column("url_pattern", sa.Text(), nullable=True),
        sa.Column("discovery_method", sa.String(length=50), nullable=True),
        sa.Column("discovered_via_pattern", sa.Text(), nullable=True),
        sa.Column("extraction_hints", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("last_success_year", sa.Integer(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dno_id"], ["dnos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_source_profile_dno_type", "dno_source_profiles", ["dno_id", "data_type"], unique=True
    )
    op.create_table(
        "dno_vnb_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dno_id", sa.Integer(), nullable=False),
        sa.Column("vnb_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("official_name", sa.String(length=255), nullable=True),
        sa.Column("homepage_url", sa.String(length=500), nullable=True),
        sa.Column("phone", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("types", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("voltage_types", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column(
            "last_synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dno_id"], ["dnos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vnb_id"),
    )
    op.create_index("idx_vnb_id", "dno_vnb_data", ["vnb_id"], unique=False)
    op.create_index(op.f("ix_dno_vnb_data_dno_id"), "dno_vnb_data", ["dno_id"], unique=True)
    op.create_table(
        "hlzf",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dno_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("voltage_level", sa.String(length=100), nullable=False),
        sa.Column("winter", sa.Text(), nullable=True),
        sa.Column("fruehling", sa.Text(), nullable=True),
        sa.Column("sommer", sa.Text(), nullable=True),
        sa.Column("herbst", sa.Text(), nullable=True),
        sa.Column("extraction_source", sa.String(length=20), nullable=True),
        sa.Column("extraction_model", sa.String(length=100), nullable=True),
        sa.Column("extraction_source_format", sa.String(length=20), nullable=True),
        sa.Column("last_edited_by", sa.String(length=255), nullable=True),
        sa.Column("last_edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_status", sa.String(length=20), nullable=False),
        sa.Column("verified_by", sa.String(length=255), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_notes", sa.Text(), nullable=True),
        sa.Column("flagged_by", sa.String(length=255), nullable=True),
        sa.Column("flagged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("flag_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dno_id"], ["dnos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_hlzf_dno_year", "hlzf", ["dno_id", "year"], unique=False)
    op.create_index("uq_hlzf_dno_year_vl", "hlzf", ["dno_id", "year", "voltage_level"], unique=True)
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dno_id", sa.Integer(), nullable=False),
        sa.Column("address_hash", sa.String(length=64), nullable=False),
        sa.Column("street_clean", sa.String(length=255), nullable=False),
        sa.Column("number_clean", sa.String(length=20), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dno_id"], ["dnos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address_hash"),
    )
    op.create_index("idx_locations_address_hash", "locations", ["address_hash"], unique=False)
    op.create_index("idx_locations_geocoord", "locations", ["latitude", "longitude"], unique=False)
    op.create_index("idx_locations_zip", "locations", ["zip_code"], unique=False)
    op.create_index(op.f("ix_locations_dno_id"), "locations", ["dno_id"], unique=False)
    op.create_table(
        "netzentgelte",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dno_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("voltage_level", sa.String(length=100), nullable=False),
        sa.Column("arbeit", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("leistung", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("arbeit_unter_2500h", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("leistung_unter_2500h", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("extraction_source", sa.String(length=20), nullable=True),
        sa.Column("extraction_model", sa.String(length=100), nullable=True),
        sa.Column("extraction_source_format", sa.String(length=20), nullable=True),
        sa.Column("last_edited_by", sa.String(length=255), nullable=True),
        sa.Column("last_edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_status", sa.String(length=20), nullable=False),
        sa.Column("verified_by", sa.String(length=255), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_notes", sa.Text(), nullable=True),
        sa.Column("flagged_by", sa.String(length=255), nullable=True),
        sa.Column("flagged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("flag_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dno_id"], ["dnos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_netzentgelte_dno_year", "netzentgelte", ["dno_id", "year"], unique=False)
    op.create_index(
        "uq_netzentgelte_dno_year_vl",
        "netzentgelte",
        ["dno_id", "year", "voltage_level"],
        unique=True,
    )
    op.create_table(
        "crawl_job_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("step_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("details", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["crawl_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crawl_job_steps_job_id"), "crawl_job_steps", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_crawl_job_steps_job_id"), table_name="crawl_job_steps")
    op.drop_table("crawl_job_steps")
    op.drop_index("uq_netzentgelte_dno_year_vl", table_name="netzentgelte")
    op.drop_index("idx_netzentgelte_dno_year", table_name="netzentgelte")
    op.drop_table("netzentgelte")
    op.drop_index(op.f("ix_locations_dno_id"), table_name="locations")
    op.drop_index("idx_locations_zip", table_name="locations")
    op.drop_index("idx_locations_geocoord", table_name="locations")
    op.drop_index("idx_locations_address_hash", table_name="locations")
    op.drop_table("locations")
    op.drop_index("uq_hlzf_dno_year_vl", table_name="hlzf")
    op.drop_index("idx_hlzf_dno_year", table_name="hlzf")
    op.drop_table("hlzf")
    op.drop_index(op.f("ix_dno_vnb_data_dno_id"), table_name="dno_vnb_data")
    op.drop_index("idx_vnb_id", table_name="dno_vnb_data")
    op.drop_table("dno_vnb_data")
    op.drop_index("idx_source_profile_dno_type", table_name="dno_source_profiles")
    op.drop_table("dno_source_profiles")
    op.drop_index(op.f("ix_dno_mastr_data_dno_id"), table_name="dno_mastr_data")
    op.drop_index("idx_mastr_nr", table_name="dno_mastr_data")
    op.drop_index("idx_mastr_acer", table_name="dno_mastr_data")
    op.drop_table("dno_mastr_data")
    op.drop_index(op.f("ix_dno_bdew_data_dno_id"), table_name="dno_bdew_data")
    op.drop_index("idx_bdew_market_function", table_name="dno_bdew_data")
    op.drop_index("idx_bdew_dno_function", table_name="dno_bdew_data")
    op.drop_index("idx_bdew_code", table_name="dno_bdew_data")
    op.drop_table("dno_bdew_data")
    op.drop_index("idx_data_sources_dno_year", table_name="data_sources")
    op.drop_table("data_sources")
    op.drop_table("crawl_jobs")
    op.drop_index(op.f("ix_system_logs_service"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_level"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_created_at"), table_name="system_logs")
    op.drop_table("system_logs")
    op.drop_index(op.f("ix_query_logs_created_at"), table_name="query_logs")
    op.drop_table("query_logs")
    op.drop_index(op.f("ix_dnos_vnb_id"), table_name="dnos")
    op.drop_index(op.f("ix_dnos_status"), table_name="dnos")
    op.drop_index(op.f("ix_dnos_slug"), table_name="dnos")
    op.drop_index(op.f("ix_dnos_region"), table_name="dnos")
    op.drop_index(op.f("ix_dnos_primary_bdew_code"), table_name="dnos")
    op.drop_index(
        "ix_dnos_name_trgm",
        table_name="dnos",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_dnos_mastr_nr"), table_name="dnos")
    op.drop_table("dnos")
    op.drop_index("idx_path_patterns_data_type", table_name="crawl_path_patterns")
    op.drop_table("crawl_path_patterns")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index("idx_api_keys_active", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_ai_provider_configs_is_enabled"), table_name="ai_provider_configs")
    op.drop_index("idx_ai_provider_enabled_priority", table_name="ai_provider_configs")
    op.drop_table("ai_provider_configs")
    # ### end Alembic commands ###
